### ISSUE TITLE
Uvoz

### ISSUE THREAD

**Issue by jaanos** [ZavbiA/APPR-2017#1]
Ukaza `View` ne vključuj v program, saj ne želiš, da se ti tabela prikaže vsakič, ko prevajaš poročilo.

Mimogrede, svoj uvoz kar vključi v poročilo (namesto `uvoz/uvoz.r` vključi svoj program) - potem lahko morda prikažeš še kako tabelo ali graf. Preostanek poročila, ki se nanaša na vzorec, za zdaj kar pobriši (boš sproti dodajala svojo vsebino).

**Comment by jaanos** [comment]
Uvoz ti trenutno ne deluje - napako dobiš v vrstici 13, ko želiš najbrž pobrisati drugi stolpec iz razpredelnice `tabela`. Poleg tega so problem še prazni znaki na koncu vrstic 24, 29 in 30, ki so se verjetno pojavili zaradi napačnega kodiranje znakov. Poskrbi, da delaš s kodiranjem znakov **UTF-8**, te prazne znake pa pobriši. Spodobilo bi se seveda, da popraviš tudi šumnike v komentarjih.

Da boš pripravljena na predstavitev naslednji teden, prosim dodaj v poročilo grafe in zemljevide, ki jih boš takrat prikazala. S številom grafov in zemljevidov seveda ni potrebno pretiravati - za vsakega pa napiši, kaj prikazuje in kaj si se iz njega naučila.

**Comment by ZavbiA** [comment]
Pri uvozu tabel imam še nekaj težav.
Tabeli 1 in 2 sem popravila in sta končani.
Pri tabeli 3 (slo.medalje) bi rada samo še iz zadnjega stolpca pobrisala imena držav.
S tabelo 4 pa imam težave že na začetku. S spletne strani https://simple.wikipedia.org/wiki/Olympic_Games bi rada uvozila tabelo (edina, ki je na tej strani), nato pa jo moram še urediti, torej pobrisati odvečne znake in podobno. Tukaj prosim za pomoč, saj se mi tabela niti ne izpiše.

**Comment by jaanos** [comment]
Pri prvi razpredelnici je še vedno problem (zdaj v vrstici 14) - najbrž želiš tam napisati `tabela[2] <- NULL`. Razpredelnica tudi ni v obliki *tidy data* - uporabi funkcijo `melt`, da dobiš stolpec z imenom spremenljivke in ga potem razbij na dva stolpca (poletne/zimske igre ter žlahtnost medalje oziroma kar uvrstitev - glej spodaj).

Pri drugi razpredelnici navajaš napačno pot datoteke CSV - imaš jo v mapi `podatki`, ne `uvoz`. Tudi to razpredelnico bo treba pretvoriti v obliko *tidy data* - stolpec z letom potem še pretvori v število.

Pri tretji razpredelnici želiš iz zadnjega stolpca ohraniti dva podatka - tip iger in leto (da lahko potem združuješ s prvo razpredelnico). Mimogrede lahko uvrstitev pretvoriš v število, npr.
```R
slo.medalje <- slo.medalje %>%
  mutate(uvrstitev = uvrstitev %>% strapplyc("^(.)") %>% unlist() %>% parse_number(),
         tip = igre %>% strapplyc("^(.)") %>% unlist(),
         leto = igre %>% strapplyc("([0-9]+)$") %>% unlist() %>% parse_number()) %>%
  select(-igre)
```
Tukaj za tip vzameš samo prvo črko, torej `P` ali `Z` - enake vrednosti uporabi tudi v prvi razpredelnici. Tudi za uvrstitve lahko uporabiš enake vrednosti.

Pri četrti razpredelnici lahko v izvorni kodi HTML podane spletne strani vidiš, da ima tabela atribut `class="wikitable"`. Poleg tega seveda podatke pridobi iz `stran4`:
```R
tabela4 <- stran4 %>% html_nodes(xpath="//table[@class='wikitable']") %>% .[[1]] %>% html_table()
```
Potem lahko naprej obdeluješ razpredelnico. Podobno kot prej jo pretvori v obliko *tidy data* - stolpci naj bodo torej leto, tip (zimske poletne), starost (mladinske/običajne), zaporedna številka (za dani tip in starost), mesto, država (in morda še podatek, ali so morda igre bile prestavljene drugam, če boš tudi take ohranila).
