### ISSUE TITLE
graf

### ISSUE THREAD

**Issue by ZavbiA** [ZavbiA/APPR-2017#2]

**Comment by ZavbiA** [comment]
Pri Analizi in vizualizaciji bi rada narisala še točkast graf, ki na x osi meri število osvojenih medalj na poletnih OI (sešteti bo potrebno bronaste, srebrne in zlate) ter na y osi število osvojenih medalj na zimskih OI. Vsi podatki so v tabela1.tidy. Težave imam s tem, kako začeti graf, da se izriše? Začela sem z g <- ggplot() + geom.point(), vendar pa karkoli sem poskušala vstaviti znotraj oklepajev, sem naletela na težave.

**Comment by jaanos** [comment]
Tako bi šlo:
```R
ggplot(tabela1.tidy %>% group_by(drzava, tip) %>% summarise(skupaj = sum(stevilo)) %>%
         dcast(drzava ~ tip, value.var = "skupaj"), aes(x = poletne, y = zimske)) + geom_point()
```
Najprej torej za vsako državo in tip izračunaš skupno število medalj, nato pa z `dcast` tipe pretvoriš v stolpce (torej ravno obratno od `melt`). Nastala stolpca lahko potem izrišeš na grafu.
