### ISSUE TITLE
Zemljevid sveta

### ISSUE THREAD

**Issue by ZavbiA** [ZavbiA/APPR-2017#3]
V projekt.Rmd sem izbrisala, kar je bilo odvečnega in uredila razdelka Izbira teme ter Obdelava, uvoz in čiščenje podatkov. Projekt se sedaj pravilno prevede.
Zdaj bi rada pri razdelku Analiza in vizualizacija naredila zemljevid sveta, ki bo prikazoval število medalj države glede na število prebivalcev. To bom naredila v datoteki vizualizacija.r.  Težave imam začeti z zemljevidom, da se kaj izriše. Kaj moram vnesti znotraj oklepaja uvozi.zemljevid() v mojem primeru?

**Comment by jaanos** [comment]
Najprej, v mapi `uvoz` imaš datoteko `uvoz_tabela1.r`, medtem ko v poročilu kličeš `uvoz_tabele1.r`. Da ti bo poročilo prevedlo, popravi ime datoteke. Ostale datoteke so pravilno navedene. V glavo bloka kode dodaj še parameter `warning = FALSE`, da ti v poročilo ne izpiše opozorila.

Kaj daš ko parametre funkcije `uvozi.zemljevid`, je odvisno od zemljevida, ki ga uvažaš. Zemljevid sveta lahko dobiš z naslova http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip - če pobereš datoteko ZIP, vidiš, da se v njej v vrhnji mapi nahaja datoteka `ne_50m_admin_0_countries.shp` - pot do nje podaš kot drugi parameter, brez končnice. Iz strani z [opisom](http://www.naturalearthdata.com/features/) zemljevidov je razvidno, da se uporablja kodiranje znakov `Windows-1252`. Zemljevid torej uvoziš tako:
```R
zemljevid <- uvozi.zemljevid("http://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip",
                             "ne_50m_admin_0_countries", encoding = "Windows-1252") %>%
  pretvori.zemljevid()
```

**Comment by ZavbiA** [comment]
Zemljevida mi še vedno ne izriše kljub temu, da sem uvozila potrebne knjižnice.
Za jutrišnjo predstavitev mi manjka samo še ta zemljevid, potem mislim, da je vse pripravljeno.
Sešteti je potrebno vse osvojene medalje iz tabela1.tidy ter narisati zemljevid glede na tabela2.tidy, kjer so shranjeni podatki o številu prebivalcev države.

**Comment by jaanos** [comment]
Kakšno napako ti pa javi? Meni izris zemljevida v `vizualizacija.r` deluje. Ali si pognala `libraries.r` (lahko poženeš kar vrstico v poročilu), da se ti uvozijo funkcije za uvoz zemljevida?

V `tabela1.tidy` imaš skupne osvojene medalje, v `tabela2.tidy` pa imaš prebivalstvo za vsako leto. Da bi bil zemljevid metodološko korekten, bi morala seštevati normirana števila medalj za vsako leto posebej. Za potrebe tega projekta bo sicer dovolj dobro tudi, če za prebivalstvo uporabiš najnovejše podatke, npr.
```R
msp <- tabela1.tidy %>% group_by(drzava) %>% summarise(medalje = sum(stevilo)) %>%
  inner_join(tabela2.tidy %>% filter(leto == 2014)) %>%
  transmute(drzava = parse_factor(drzava, levels(zemljevid$name_long)),
            msp = medalje / stevilo_prebivalcev)
ggplot() + geom_polygon(data = zemljevid %>% left_join(msp, by = c("name_long" = "drzava")),
                        aes(x=long, y=lat, group=group, fill = msp * 1000000)) +
  guides(fill = guide_colorbar(title = "Medalje na milijon prebivalcev")) +
  scale_fill_gradient(limits = c(0, 100))
```
Če pogledaš v razpredelnico `msp`, vidiš, da ima Liechtenstein (ki je tako ali tako premajhen, da bi ga bilo videti na zemljevidu) daleč največje razmerje - zato je tudi postavljena zgornja meja lestvice na 100 (druga je Norveška, ki ima razmerje nekoliko pod 100). V poročilu to vsekakor omeni.

Izrisani zemljevid sicer ne prikaže vseh držav, saj se imena nekaterih razlikujejo med razpredelnicami. Za začetek lahko preveriš, katere države so v `tabela1.tidy`, ne pa tudi v `tabela2.tidy` - nekatere se sicer nanašajo na bivše države ali provizorične olimpijske ekipe, nekatere pa so pod drugim imenom v `tabela2.tidy`:
```R
drz <- unique(tabela1.tidy$drzava)
drz[! drz %in% tabela2.tidy$drzava]
```
Take države preimenuj v eni ali drugi razpredelnici (pomagaj si z `gsub`), da se bodo imena ujemala in se bodo te države torej pojavile v razpredelnici `msp`. Poskrbi, da se bodo ta imena ujemala tudi z imeni v zemljevidu:
```R
levels(zemljevid$name_long)
```
Izmed tistih imen, ki se pojavijo tako v `tabela1.tidy` kot tudi v `tabela2.tidy`, ni nobenega takega, ki ga ne bi bilo v zemljevidu (sicer bi `parse_factor` dal opozorilo). Da ti bo v `tabela1.tidy` pravilno uvozilo `Côte d'Ivoire`, v `uvoz_tabela1.r` v vrstici 28 popravi regularni izraz na `"([[:alpha:]' ]+)"` (torej da poleg črk in presledka dovoli še apostrof).

Mimogrede, po koncu vsakega bloka kode v poročilu pusti prazno vrstico, saj se lahko sicer besedilo za tabelo napačno prikaže (konkretno se problem pojavi po `tabela4.tidy`).

**Comment by ZavbiA** [comment]
Prosim, preverite, če zdaj vse pravilno deluje. Sem popravila tudi vsa imena držav, ki se niso ujemala. Ostale države ne obstajajo.
Najlepša hvala za pomoč.

**Comment by jaanos** [comment]
Zdaj ti prevede poročilo, tako da bom dodal povezavo do trenutnega commita dodal na [repozitorij za zagovore](https://github.com/jaanos/APPR-2017-zagovori). Če boš do predstavitve še kaj spreminjala, odpri issue na repozitoriju za zagovore, da posodobim povezavo - tam si preberi natančnejša navodila.

Še to bi pripomnil: da ne dobiš opozorila ob uvozu, v glavo bloka kode, kjer kličeš uvoz, dodaj parameter `warning = FALSE` (glej prvi odgovor v tej zadevi). Da ti ne izpiše kode ob risanju grafa, v glavo bloka kode dodaj parameter `echo = FALSE`.

**Comment by ZavbiA** [comment]
Sem dodala še ta dva parametra.

**Comment by jaanos** [comment]
V redu, bom posodobil povezavo.

**Comment by ZavbiA** [comment]
Imam še eno vprašanje - vam ko poženete projekt.Rmd, izriše zemljevid? Meni ga namreč ne in ne vem, ali se je to zgodilo, ker sem kaj spremenila, ali na splošno ne izriše? V vizualizacija.r ga imam pod plots, vendar bi rada, da se izriše, ko poženem dokument projekt.Rmd.

**Comment by ZavbiA** [comment]
Mislim, da sem rešila problem. Vam pošljem novo šifro na repozitorij za zagovore. Prosim, še enkrat preverite, če vse v redu deluje in izriše zemljevid.

**Comment by jaanos** [comment]
Meni prikaže zemljevid - ga je prikazalo že pred zadnjim commitom.
