### ISSUE TITLE
graf slo.medalje

### ISSUE THREAD

**Issue by ZavbiA** [ZavbiA/APPR-2017#4]
Rišem nov graf v svojem projektu in sicer bi rada naredila stolpčni diagram. Podatke pobiram iz tabele slo.medalje (uvoz/uvoz_tabele3.r). Na x osi bi rada imela imena športov, na y osi pa število medalj oz. uvrstitev med 3 (stolpec uvrstitev iz tabele slo.medalje), to pa tako, da je vsak stolpec iz treh barv - za 1, 2 in 3. mesto. Težave imam predvsem s tem, kako razdeliti vsak stolpec na 3 dele.

**Comment by jaanos** [comment]
Nekako tako bi šlo:
```R
ggplot(slo.medalje, aes(x = reorder(sport, mapply(paste, uvrstitev, sport),
                                    . %>% { -(length(.)^3 +
                                                length(.) * length(.[grepl("^1", .)]) +
                                                length(.[grepl("^2", .)])) }),
                        fill = factor(uvrstitev))) + geom_bar() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  xlab("Šport") + ylab("Število medalj") + guides(fill = guide_legend(title = "Uvrstitev"))
```
Vse, kar rabiš, da ti dele stolpca pobrava glede na medaljo, je to, da podaš ustrezno vrednost pri parametru `fill` (pretvorba v `factor` je potrebna zato, da `ggplot2` dodeli različne barve in ne samo odtenkov). Zakomplicirani del tukaj je urejanje - trenutno naredi tako, da uredi najprej po skupnem številu medalj, nato po zlatih in nazadnje po srebrnih (členi so nastavljeni tako, da s povečanjem enega člena naslednjega ni mogoče toliko zmanjšati, da bi bila celotna vsota manjša).

Mimogrede, podatke še malo uredi - opažam, da se judo pojavi dvakrat (enkrat z malo, enkrat z veliko začetnico), prav tako športna gimnastika in kajak-kanu slalom (s pomišljajem ali brez).

**Comment by ZavbiA** [comment]
Sem popravila tabelo in uredila graf. Hvala.
