### ISSUE TITLE
brisanje vrstic v 2.razpredelnici

### ISSUE THREAD

**Issue by ZavbiA** [ZavbiA/APPR-2017#5]
V drugi razpredelnici (tabela2.tidy) sem opazila, da imajo nekatere države v stolpcu stevilo_prebivalcev vrednost NA (najbrž zato, ker takrat še niso obstajale in ni podatkov). Ker jih je veliko, jih ne bi vsake posebej ročno brisala. Kako ukažem, da pobriše vrstice s temi vrednostmi?

Poleg tega bi za Eritreo rada ročno vnesla podatek o številu prebivalcev v letu 2014 (Eritrea že ima svojo vrstico za 2014, vendar je vrednost NA). Kako to naredim?

**Comment by jaanos** [comment]
Tako lahko narediš oboje hkrati:
```R
tabela2.tidy <- tabela2.tidy %>% drop_na() %>%
  add_row(drzava = "Eritrea", leto = 2014, stevilo_prebivalcev = 1234567)
```
Seveda vstavi dejansko število. Za funkcijo `drop_na` potrebuješ knjižnico `tidyr`.

**Comment by ZavbiA** [comment]
Kljub temu, da sem uvozila knjižnico tidyr, mi še vedno izpiše:
Error in function_list[[i]](value) : could not find function "drop_na".
Je mogoče problem v starejši verziji R-a?

Tudi če izbrišem ukaz drop_na, mi pri zagonu projekta projekt.rmd, javi "could not find function "add_row"", kljub temu, da mi v uvoz_tabela1.r in uvoz_tabele2.r ta funkcija deluje.

**Comment by jaanos** [comment]
Verjetno je krivo to, da nimaš najnovejših različic knjižnic `tidyr` in `tibble`, kjer se ti funkciji nahajata. V izogib morebitnim težavam svetujem, da posodobiš kar vse knjižnice. V meniju *Tools* izberi možnost *Check for Package Updates...*, nato pa s klikom na *Select All* izbereš vse posodobitve (med njimi bi morali biti tudi prej omenjeni knjižnici). Postopek bo sicer trajal nekaj časa, a potem bi moralo delovati.

Če ti posodobitve ne začne (prej te bo vprašalo, ali želiš ponovno zagnati R, na kar odgovoriš pritrdilno), poskusi prej še počistiti delovno okolje (v zavihku **Environment** levo zgoraj klikni na metlo) ali zapreti projekt (klikni desno zgoraj, kjer je ime projekta, in izberi *Close Project*).

**Comment by ZavbiA** [comment]
Funkcija add_row zdaj deluje, vendar pa še vedno javi napako: could not find function "drop_na".
Zato sem s funkcijo tabela2.tidy[!complete.cases(tabela2.tidy),] poiskala vrstice z vrednostjo NA in jih pobrisala.
