### ISSUE TITLE
Tabela stroškov olimpijskih iger

### ISSUE THREAD

**Issue by ZavbiA** [ZavbiA/APPR-2017#6]
Na spletnem naslovu https://arxiv.org/ftp/arxiv/papers/1607/1607.04484.pdf na strani 9 sem našla uporabno tabelo o stroških organizacije OI, ki bi jo rada vključila v svoj projekt. Težava je v tem, da je tabela v pdf obliki. Jo vseeno lahko snamem?

**Comment by jaanos** [comment]
Verjetno bo najlažje, če jo skopiraš v Excel, shraniš v CSV in jo kot tako uvoziš.

**Comment by ZavbiA** [comment]
Tabelo sem uvozila. Težave imam v zadnjem stolpcu, kjer za 5 držav ni podatka o stroških organizacije. Te podatke sem želela nato ročno vnesti, vendar sem ugotovila, da jih ni z razlogom - npr. Mehiški peso in Jugoslovanski dinar sta doživela hiperinflacijo, zaradi česar podatki niso relevantni (stroški so namreč računani na ameriški dolar 2015). Kaj svetujete, da naredim s tem zadnjim stolpcem oz. z vrednostmi, ki manjkajo?

**Comment by jaanos** [comment]
Verjetno bo najbolje, da pač pustiš manjkajoče podatke (`NA`). Če te bo to motilo pri analizi, lahko te države izpustiš, pa v besedilu pojasniš, kaj se dogaja oz. zakaj teh podatkov ni.

**Comment by ZavbiA** [comment]
V redu, bom pustila tako kot je.

Zdaj rišem graf za to tabelo. Zaenkrat imam:
ggplot(tabela5.tidy %>% filter(tip=="P")) + aes(x=leto, y=st_dogodkov) + geom_line(color="red") + xlab("leto") + ylab("") + ggtitle("Naraščanje števila dogodkov, števila udeležencev in stroškov")

Rada bi v isti graf dorisala še krivuljo števila udeležencev in krivuljo stroškov. Vse 3 krivulje moram razdeliti na poletne (P) in zimske (Z) igre. Tako pride 6 krivulj. Upam, da to ni preveč? Kako vse spravim v en graf?

**Comment by ZavbiA** [comment]
Sem popravila graf, da izriše za poletne in zimske posebej:
tabela5.tidy %>%
  ggplot(aes(x=leto, y=st_dogodkov, colour=tip)) +
  geom_line() + xlab("leto") + ylab("") +
  ggtitle("Naraščanje števila dogodkov, števila udeležencev in stroškov")

Kako zdaj dodam še krivulje za st_nastopajocih in stroske?

**Comment by jaanos** [comment]
Najprej, `uvoz_tabele5.r` mi ne deluje, ker se sklicuješ na `tabela5` - najbrž želiš tam `tabela5.tidy`. Po izvedbi preostalih ukazov ostane notri še vrstici za `Average`. Raje, kot da brišeš po številki vrstice, briši po vrednosti, npr.
```R
tabela5.tidy <- tabela5.tidy %>% filter(! mesto %in% c("Average", "Median"))
```
Poskrbi še, da bo stolpec za leto pretvorjen v števila.

Da bi na istem grafu predstavljala še število nastopajočih in stroške, odsvetujem, saj gre za podatke v različnih skalah. Tako raje za vsak podatek naredi svoj graf. Če želiš primerjati dva izmed teh podatkov med seboj, raje nariši enega na os x, drugega na os y (morda lahko vseeno prikažeš te podatke skozi čas - da vidiš, da dejansko naraščajo).

**Comment by ZavbiA** [comment]
Hvala, to je urejeno.

**Comment by ZavbiA** [comment]
Vidim, da bi se vseeno dalo združiti število dogodkov in število nastopajočih v en graf. Za število nastopajočih bi npr. spremenila obliko krivulje. Bi to šlo? S kakšnimi ukazi združim ta dva podatka v en graf?
