### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by ZavbiA** [ZavbiA/APPR-2017#7]
Za zaključek bi rada naredila še aplikacijo v shiny-ju. Iz trenutnih podatkov ne uspem dobiti dobre ideje, kaj sprogramirati. Sem pa razmišljala, da bi za nekaj držav (npr.za uspešnejše države) dodatno uvozila podatke o številu posameznih medalj po letih ter tako sestavila aplikacijo, kjer se lahko izbere eno od teh držav in zraven izriše graf (npr.tak, kot sem ga naredila za število osvojenih medalj Slovencev na OI, le da bi bile na x osi letnice namesto športnih disciplin). Kaj menite?

**Comment by ZavbiA** [comment]
Druga ideja pa je, da za posamezne olimpijske igre prikažem različne podatke - z izbiro letnice se prikaže tabela s podatki o npr. tipu, državi, mestu, številu dogodkov, številu udeležencev, stroških... Ta ideja je najbrž boljša glede na to, da imam potrebne podatke že uvožene.

**Comment by jaanos** [comment]
Obe ideji sta v redu - morda bi s prvo dejansko lahko pokazala kaj več, kot lahko vidiš iz ene same tabele. Lahko seveda narediš tudi oboje (npr. vsako v enem zavihku).

**Comment by ZavbiA** [comment]
Lotila sem se prve ideje. Na Wikipediji imam 10 tabel za olimpijske igre od leta 2000 dalje in sicer za najuspešnejših 20-30 držav po medaljah. Teh 10 tabel bi rada združila v eno tabelo - vse tabele so istega tipa oz. imajo iste stolpce. Tukaj sta naslova dveh takih tabel: https://en.wikipedia.org/wiki/2014_Winter_Olympics_medal_table , https://en.wikipedia.org/wiki/2010_Winter_Olympics_medal_table.
Kako združim vse tabele v eno? Moram najprej uvozit vsako tabelo posebej? (vsaki tabeli posebej je treba dodati le še stolpec z letnico, potem so združljive)

**Comment by jaanos** [comment]
Najlažje bo, če napišeš funkcijo, ki ji podaš letnico, ta pa z ustreznega naslova pridobi tabelo in ji doda še stolpec z letom (in tipom OI, če boš uvažala tudi za poletne igre) ter vrne tako tabelo. Potem lahko uporabiš `lapply`, ki mu podaš vektor let in tvojo funkcijo - rezultat bo seznam razpredelnic. Te razpredelnice lahko potem v eno združiš s funkcijo `bind_rows`.

**Comment by ZavbiA** [comment]
Spomnila sem se, kako bom združila obe ideji za Shiny: z izbiro letnice (od 2000 dalje) se bodo prikazali podatki o igrah v tistem letu (tip, država in mesto, št. dogodkov, št. udeležencev, stroški), zraven pa še graf števila osvojenih medalj najuspešnejših držav (upoštevajoč tudi lesk medalje) - tak graf kot je na naslovu https://en.wikipedia.org/wiki/File:Olympics_2016_Medals.svg.

**Comment by ZavbiA** [comment]
Tabele sem naredila vsako posebej. Imam jih shranjene kot tabela1, tabela2, tabela3, itd. Kako jih lahko združim v eno tabelo? Med seboj se seveda ujemajo po stolpcih.

**Comment by ZavbiA** [comment]
Na repozitorij sem dodala uvoz_shiny.r, kjer naj bi uvozila te skupne tabele. Prosim, če lahko pogledate, zakaj ne deluje.

**Comment by jaanos** [comment]
Najprej, da ti bo funkcija `uvoz_tabel_wiki` sploh vračala razpredelnico, na konec dodaj še `return(tabela)`. Problem je še s tabelo za leto 2016 - zaradi zadnje vrstice se stolpec s številom zlatih medalj ne pretvori v števila in ti tako `melt` spravi razpredelnico v drugačno obliko. Če sama poskrbiš za pretvorbo v števila, potem deluje.

Mimogrede, poročila ti trenutno ne prevede - problem so prazni znaki na začetku vrstice 92 v `projekt.Rmd`. Najbolje bo, če pobrišeš vse znake pred `dcast` in jih nadomestiš s presledki.

**Comment by ZavbiA** [comment]
To bi zdaj moralo biti urejeno.

Težave imam z izrisom grafa v shiny-ju. Kako lahko narišem stolpčni graf, ki bo imel v vsakem stolpcu število zlatih, srebrnih in bronastih medalj obarvano posebej (podobno kot graf2 v mojem poročilu)?

**Comment by jaanos** [comment]
Najprej, v sami Shiny aplikaciji ne kliči svojih programov - aplikacijo boš vključila v poročilo z blokom kode, kot npr.
```R
    ```{r shiny, echo=FALSE}
    shinyAppDir("shiny", options = list(width = "100%", height = 500))
    ```
```
(brez zamika na začetku vrstic). Tako bodo ob zagonu aplikacije vsi podatki že uvoženi. Če želiš aplikacijo poganjati posebej, poskrbi, da ima na voljo potrebne podatke (najlažje bo, če poženeš vse ukaze `source` iz poročila).

Risanje grafa bi šlo nekako tako:
```R
    medalje <- skupna_tabela %>% filter(leto %in% input$leto) %>%
      group_by(drzava, lesk) %>% summarise(stevilo = sum(stevilo))
    maxst <- medalje %>% group_by(drzava) %>% summarise(stevilo = sum(stevilo)) %>%
      summarise(stevilo = max(stevilo)) %>% .$stevilo
    ggplot(medalje,
           aes(x = reorder(drzava,
                           -sapply(drzava,
                                   . %>% { filter(medalje, drzava == .) %>%
                                             arrange(desc(lesk)) %>% .$stevilo } %>%
                                     { .[1]*maxst^2 + .[2]*maxst + .[3] })),
               y = stevilo, fill = factor(lesk, c("zlate", "srebrne", "bronaste")))) +
      geom_col(position = "dodge") + ylab("Število osvojenih medalj") + xlab("Država") +
      guides(fill = guide_legend(title = "Medalje"))
```
Glede na to, da v `ui.R` dovoliš izbiro več let, pri `filter` uporabiš operator `%in%`. Ker imaš za razliko od `graf2` tukaj številke namesto seznama vseh medalj, namesto `geom_bar` uporabiš `geom_col`. Na podoben način se naredi tudi preurejanje, le da tukaj upošteva številke in ne dolžin seznamov (`maxst` je največje število medalj, ki jih je dosegla katerakoli država - s tem podatkom dosežeš, da najprej urejaš po številu zlatih, nato srebrnih in nazadnje bronastih medalj). Seveda bi se risanje grafa bistveno poenostavilo, če ne bi urejala držav.

**Comment by ZavbiA** [comment]
V poročilu se mi zdaj izpisuje
ERROR: unused argument (choises = c(2000, 2002, 2004, 2006, 2008, 2010, 2012, 2014, 2016)).
V čem je težava?

**Comment by jaanos** [comment]
Zamenjaj `choises` s `choices` in `mailPanel` z `mainPanel`, pa bo delovalo.

**Comment by ZavbiA** [comment]
Se opravičujem, res je šlo le za slovnične napake. Zdaj se pojavi problem Error: could not find function "geom_col". Moram uvozit še kakšno knjižnico?

**Comment by jaanos** [comment]
Morda nimaš najnovejše različice knjižnice `ggplot2`. Sicer pa lahko namesto `geom_col` uporabiš tudi `geom_bar` s parametrom `stat = "identity"`.

**Comment by ZavbiA** [comment]
Najlepša hvala! Poročilo imam zdaj zaključeno.

**Comment by jaanos** [comment]
V redu - na poročilo nimam pripomb, tako da bom dodal povezavo na repozitorij za zagovore. S profesorjem se lahko domeniš za termin zagovora.

Če boš še kaj spreminjala, mi javi, da posodobim povezavo.

**Comment by ZavbiA** [comment]
Ravnokar sem posodobila svoj projekt. V shiny aplikaciji sem dodala tabelo, ki izpiše podatke o tipu iger ter mestu in državi prireditve. Prosim, poglejte če je smiselno.

**Comment by jaanos** [comment]
Svetoval bi, da v prikazani tabeli prikažeš še leto in po njem urediš (uporabi `arrange`).
